### ISSUE TITLE
Habit name cannot be 1 character long

### ISSUE THREAD

**Issue by niktss** [willbsp/habits#21]
Glad to see a new habit app on FDroid!

One issue I've noticed is the habit name cannot be a single character, like '1' or '£' - the field just goes red when the confirm button is pressed. 

If this is an intentional design decision, it would be better for there to be a popup explaining the habit name rules, and maybe make the tinted border more prominent - my Material You colours for example made it very hard for me to realise there even was an error 😅:

![Screenshot_20230723_090120_Habits](https://github.com/willbsp/habits/assets/57101103/55fae56b-b68c-4576-a8a8-01da789dba1a)

![Screenshot_20230723_090122_Habits](https://github.com/willbsp/habits/assets/57101103/2e346d07-fbe4-41cb-85d5-5ca1b3a06c36)

**Comment by willbsp** [comment]
Hi, the one character limit was an intentional decision, however there is definitely room for improvement so that the user gets some form of feedback when inputting an invalid habit name. I am going to close this issue and make a separate [issue](https://github.com/willbsp/habits/issues/24) for this feature.
Thank you for the feedback!
